### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by daxida** [Andriamanitra/clash#40]
Update the README with some documentation for the new justfile and other features that were implemented (`clash showtest` etc.).

**Comment by Andriamanitra** [comment]
More things to document:
- [x] Asciinema demo of the most important commands
- [x] How to contribute (installing requirements, use of rustfmt, clippy, etc)
- [x] Generating shell completions
- [x] Better explanation of how the tool works (clash storage directory, downloading clashes)

**Comment by Andriamanitra** [comment]
I think this issue is addressed by the updated README and the wiki.
